project:
  type: website 
  output-dir: docs

website:
  title: "Tianen (Evan) Hao's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd
      - text: "CV"
      - resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

